---
name: Dropbox Sync
version: dev
slug: dropbox_sync
description: Upload your Home Assistant backups to Dropbox
url: "https://github.com/jaseonline/addon-dropbox-sync/"
arch:
  - aarch64
  - amd64
  - armhf
  - i386
stdin: true
hassio_api: true
hassio_role: manager
boot: auto
map:
  - backup
  - share
options:
  oauth_access_token: "<DROPBOX_TOEN>"
  output: ""
schema:
  oauth_access_token: str
  output: str
  keep_last: int(0,)?
  filetypes: str?
